name: Oras Auth Tests
on:
  pull_request: []

jobs:
  test-auth:
    runs-on: ubuntu-latest
    services:
      registry:
        image: ghcr.io/oras-project/registry:latest
        env:
          REGISTRY_AUTH: "{htpasswd: {realm: localhost, path: /etc/docker/registry/auth.htpasswd}}"
        ports:
          - 5000:5000
        volumes:
          - auth.htpasswd:/etc/docker/registry/auth.htpasswd
        options: --name registry

    steps:
      - uses: actions/checkout@v3
      - name: Setup Authentication
        run: |
           rm -rf auth.htpasswd
           htpasswd -cB -b auth.htpasswd myuser mypass
      - name: Restart registry
        uses: docker://docker
        with:
          args: docker restart registry
      - name: Setup Environment
        run: conda create --quiet --name oras requests
      - name: Test Oras Python with Auth
        env:
          registry_host: localhost
          registry_port: ${{ job.services.registry.ports[5000] }}
          with_auth: true
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate oras
          pip install --upgrade pip setuptools
          make install
          make test
